name: Unity WebGL Build

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:

jobs:
  buildWebGL:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download AssetPacks.zip from Google Drive
        run: |
          sudo apt-get install -y unzip curl
          FILE_ID="1yD2tK7ABZxTakIah7dPb40P02uDiGo0G"
          FILE_NAME="AssetPacks.zip"
          curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${FILE_ID}" > /tmp/intermediate.html
          CONFIRM_CODE=$(grep -o 'confirm=[^&]*' /tmp/intermediate.html | sed 's/confirm=//')
          echo "Confirm Code: ${CONFIRM_CODE}"
          echo "https://drive.google.com/uc?export=download&confirm=${CONFIRM_CODE}&id=${FILE_ID}"
          curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=${CONFIRM_CODE}&id=${FILE_ID}" -o ${FILE_NAME}
          unzip -o ${FILE_NAME} -d Assets/AssetPacks

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('**/Assets/**', '**/Packages/**', '**/ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL